name: Deploy to VM workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sber

    steps:      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        
    - name: Deploy to VM server
      run: |
        ssh -o StrictHostKeyChecking=no $VM_USER@$VM_SERVER "cd /home/$VM_USER/$GITHUB_REPOSITORY.git && git pull"
